[tool.altair.tasks]
lint = ["ruff check"]
format = ["ruff format --diff --check"]
ruff-fix = ["ruff check", "ruff format"]
type-check = ["mypy altair tests"]
pytest = ["pytest"]
test = ["lint", "format", "type-check", "pytest"]
test-fast = ["ruff-fix", "pytest -m \"not slow\""]
test-slow = ["ruff-fix", "pytest -m \"slow\""]
generate-schema-wrapper = [
    "mypy tools",
    "python tools/generate_schema_wrapper.py",
    "test",
]
update-init-file = ["python tools/update_init_file.py", "ruff-fix"]
doc-clean = [
    "python -c \"import shutil;shutil.rmtree('doc/_build', ignore_errors=True)\"",
]
doc-clean-generated = [
    "python -c \"import shutil;shutil.rmtree('doc/user_guide/generated', ignore_errors=True)\"",
    "python -c \"import shutil;shutil.rmtree('doc/gallery', ignore_errors=True)\"",
]
doc-clean-all = [
    "doc-clean",
    "doc-clean-generated",
    "python -c \"import shutil;shutil.rmtree('doc/_images', ignore_errors=True)\"",
]
doc-serve = [
    "python -m http.server --bind \"127.0.0.1\" --directory doc/_build/html 8000",
]
doc-publish = ["python tools/sync_website.py --no-commit"]
clean = [
    "python -c \"import shutil;shutil.rmtree('dist', ignore_errors=True)\"",
]
build = ["clean", "uv build"]
publish = ["build", "uv publish"]
export-tasks = [
    "python -c \"from tools.tasks import app;app.to_path('tasks.toml')\"",
]

[tool.altair.tasks.doc-build-html]
commands = [
    "python -c \"from pathlib import Path;Path('doc/_images').mkdir(parents=True, exist_ok=True)\"",
    "sphinx-build -b html -d doc/_build/doctrees doc doc/_build/html",
]
extras = ["doc"]

[tool.altair.tasks.doc-clean-build]
commands = ["doc-clean-all", "doc-build-html"]
extras = ["doc"]

[tool.altair.tasks.doc-publish-clean-build]
commands = ["doc-clean-build", "doc-publish"]
extras = ["doc"]
